"""Secure, terminal-bound personal-PIN login for the shared URY POS.

PIN login is only offered on a device that has first been enrolled against a
pre-provisioned `URY POS Terminal`. Enrollment exchanges a short-lived,
single-use code (generated by staff in Desk) for a long-lived device credential
that is stored server-side as a hash and on the device as an httpOnly cookie.

Every PIN attempt therefore requires a valid device credential *before* the PIN
is checked, the pool of accepted PINs is scoped to the terminal's Branch, and
per-terminal lockout (independent of the client IP, which is dynamic on these
terminals) throttles brute force. Failures and successes are written to
`URY POS PIN Audit`.
"""

import frappe
from frappe import _
from frappe.auth import LoginManager
from frappe.core.doctype.activity_log.activity_log import add_authentication_log
from frappe.rate_limiter import rate_limit
from frappe.utils import now_datetime
from frappe.utils.password import check_password

from ury.ury.doctype.ury_pos_pin_settings.ury_pos_pin_settings import (
	PIN_AUTH_FIELD,
	PIN_MAX_LENGTH,
	PIN_MIN_LENGTH,
	is_eligible_pos_user,
	is_user_in_branch,
)
from ury.ury.doctype.ury_pos_terminal.ury_pos_terminal import hash_secret


PIN_SETTINGS_DOCTYPE = "URY POS PIN Settings"
TERMINAL_DOCTYPE = "URY POS Terminal"
AUDIT_DOCTYPE = "URY POS PIN Audit"
GENERIC_PIN_ERROR = "Invalid PIN or PIN login is not available."
GENERIC_ENROLL_ERROR = "Enrollment failed. Check the terminal and code, then ask a manager for a new code."

TERMINAL_COOKIE = "ury_pos_terminal"
TERMINAL_COOKIE_MAX_AGE = 400 * 24 * 60 * 60  # ~13 months
ENROLLMENT_CODE_TTL_MINUTES = 10

# Per-terminal lockout. Independent of client IP because POS terminals sit
# behind dynamic IPs; the device credential is the stable identity we throttle.
LOCK_FAIL_WINDOW_SECONDS = 300
LOCK_FAIL_THRESHOLD = 8
LOCK_BASE_SECONDS = 60
LOCK_MAX_SECONDS = 900


# ---------------------------------------------------------------------------
# Eligibility (branch scoped)
# ---------------------------------------------------------------------------

def _eligible_settings(branch: str):
	rows = frappe.get_all(
		PIN_SETTINGS_DOCTYPE,
		filters={"enabled": 1},
		fields=["name", "user"],
		order_by="modified desc",
	)
	return [
		row
		for row in rows
		if is_eligible_pos_user(row.user) and is_user_in_branch(row.user, branch)
	]


def _find_user_for_pin(pin: str, branch: str):
	for row in _eligible_settings(branch):
		try:
			check_password(
				row.name,
				pin,
				doctype=PIN_SETTINGS_DOCTYPE,
				fieldname=PIN_AUTH_FIELD,
				delete_tracker_cache=False,
			)
			return row.user
		except frappe.AuthenticationError:
			continue
	return None


# ---------------------------------------------------------------------------
# Terminal binding (device credential in httpOnly cookie)
# ---------------------------------------------------------------------------

def _get_cookie(name: str):
	request = getattr(frappe.local, "request", None)
	if not request:
		return None
	return request.cookies.get(name)


def _cookie_is_secure() -> bool:
	request = getattr(frappe.local, "request", None)
	return bool(request and request.scheme == "https")


def _set_terminal_cookie(raw_credential: str) -> None:
	cookie_manager = getattr(frappe.local, "cookie_manager", None)
	if not cookie_manager:
		return
	# Store only the opaque credential: a plain hex string needs no encoding, so
	# it round-trips through Set-Cookie/Cookie without a fragile delimiter.
	cookie_manager.set_cookie(
		TERMINAL_COOKIE,
		raw_credential,
		max_age=TERMINAL_COOKIE_MAX_AGE,
		httponly=True,
		secure=_cookie_is_secure(),
		samesite="Strict",
	)


def _resolve_terminal_from_cookie():
	raw = _get_cookie(TERMINAL_COOKIE)
	if not raw:
		return None

	name = frappe.db.get_value(
		TERMINAL_DOCTYPE,
		{"credential_hash": hash_secret(raw), "enabled": 1},
		"name",
	)
	if not name:
		return None
	return frappe.get_doc(TERMINAL_DOCTYPE, name)


# ---------------------------------------------------------------------------
# Lockout (per terminal, cache backed)
# ---------------------------------------------------------------------------

def _lock_keys(terminal_id: str):
	safe = frappe.scrub(terminal_id)
	return (
		f"ury_pos_pin:fail:{safe}",
		f"ury_pos_pin:lock:{safe}",
		f"ury_pos_pin:locklevel:{safe}",
	)


def _is_terminal_locked(terminal_id: str) -> bool:
	_, lock_key, _ = _lock_keys(terminal_id)
	return bool(frappe.cache().get_value(lock_key))


def _register_terminal_failure(terminal_id: str) -> None:
	fail_key, lock_key, level_key = _lock_keys(terminal_id)
	cache = frappe.cache()
	fails = (cache.get_value(fail_key) or 0) + 1
	cache.set_value(fail_key, fails, expires_in_sec=LOCK_FAIL_WINDOW_SECONDS)

	if fails >= LOCK_FAIL_THRESHOLD:
		level = (cache.get_value(level_key) or 0) + 1
		lock_seconds = min(LOCK_BASE_SECONDS * (2 ** (level - 1)), LOCK_MAX_SECONDS)
		cache.set_value(lock_key, 1, expires_in_sec=lock_seconds)
		cache.set_value(level_key, level, expires_in_sec=LOCK_MAX_SECONDS * 4)
		cache.delete_value(fail_key)


def _clear_terminal_failures(terminal_id: str) -> None:
	for key in _lock_keys(terminal_id):
		frappe.cache().delete_value(key)


# ---------------------------------------------------------------------------
# Audit
# ---------------------------------------------------------------------------

def _record_audit(status: str, *, terminal=None, user: str = "Guest", reason: str = "") -> None:
	# No user switching here: this runs right after login_as() on success, and
	# calling frappe.set_user() at that point corrupts the freshly created
	# session. ignore_permissions is enough for this internal read-only log.
	frappe.get_doc(
		{
			"doctype": AUDIT_DOCTYPE,
			"event_time": now_datetime(),
			"status": status,
			"terminal": terminal.name if terminal else None,
			"terminal_id": terminal.terminal_id if terminal else None,
			"pos_user": user,
			"reason": reason,
			"ip_address": getattr(frappe.local, "request_ip", None),
			"user_agent": frappe.get_request_header("User-Agent"),
		}
	).insert(ignore_permissions=True)


def _record_login(subject: str, user: str, status: str) -> None:
	add_authentication_log(subject, user, operation="Login", status=status)


def _reject_pin_login(terminal=None, reason: str = "invalid_pin", audit_status: str = "Failed"):
	# Preserve the audit trail even though the request ends in an
	# AuthenticationError and its transaction is rolled back.
	_record_login("URY POS PIN login failed", "Guest", "Failed")
	_record_audit(audit_status, terminal=terminal, reason=reason)
	frappe.db.commit()  # nosemgrep
	frappe.flags.disable_traceback = True
	frappe.throw(_(GENERIC_PIN_ERROR), frappe.AuthenticationError)


# ---------------------------------------------------------------------------
# Whitelisted endpoints
# ---------------------------------------------------------------------------

@frappe.whitelist(allow_guest=True, methods=["GET"])
def get_pin_login_status():
	"""Tell the POS whether to show the enrollment screen, the PIN keypad, or
	neither. Exposes no account list."""
	authenticated = frappe.session.user != "Guest"
	terminal = _resolve_terminal_from_cookie()

	if not terminal:
		return {
			"enabled": False,
			"authenticated": authenticated,
			"enrollment_required": not authenticated,
			"min_length": PIN_MIN_LENGTH,
			"max_length": PIN_MAX_LENGTH,
		}

	return {
		"enabled": bool(_eligible_settings(terminal.branch)),
		"authenticated": authenticated,
		"enrollment_required": False,
		"min_length": PIN_MIN_LENGTH,
		"max_length": PIN_MAX_LENGTH,
	}


@frappe.whitelist(methods=["POST"])
def generate_terminal_enrollment_code(terminal: str):
	"""Staff-only: mint a short-lived, single-use enrollment code shown in Desk
	and typed once on the device to bind it."""
	doc = frappe.get_doc(TERMINAL_DOCTYPE, terminal)
	if not frappe.has_permission(TERMINAL_DOCTYPE, "write", doc):
		frappe.throw(_("Not permitted"), frappe.PermissionError)

	raw_code = doc.issue_enrollment_code()
	return {
		"terminal_id": doc.terminal_id,
		"code": raw_code,
		"expires_in_minutes": ENROLLMENT_CODE_TTL_MINUTES,
	}


@frappe.whitelist(allow_guest=True, methods=["POST"])
@rate_limit(limit=10, seconds=60 * 60, methods=["POST"], ip_based=True)
def enroll_terminal(terminal_id: str, code: str):
	"""Guest device: exchange a valid enrollment code for a device credential,
	returned as an httpOnly cookie. The raw code is single use."""
	terminal_id = str(terminal_id or "").strip()
	code = str(code or "").strip()
	if not terminal_id or not code:
		frappe.throw(_(GENERIC_ENROLL_ERROR), frappe.AuthenticationError)

	name = frappe.db.get_value(
		TERMINAL_DOCTYPE, {"terminal_id": terminal_id, "enabled": 1}, "name"
	)
	if not name:
		frappe.throw(_(GENERIC_ENROLL_ERROR), frappe.AuthenticationError)

	terminal = frappe.get_doc(TERMINAL_DOCTYPE, name)
	if not terminal.verify_enrollment_code(code):
		frappe.throw(_(GENERIC_ENROLL_ERROR), frappe.AuthenticationError)

	raw_credential = terminal.issue_credential()
	terminal.touch_last_seen()
	_set_terminal_cookie(raw_credential)
	frappe.db.commit()  # nosemgrep

	return {
		"terminal_id": terminal.terminal_id,
		"terminal_name": terminal.terminal_name,
		"branch": terminal.branch,
	}


@frappe.whitelist(allow_guest=True, methods=["POST"])
@rate_limit(limit=5, seconds=60, methods=["POST"], ip_based=True)
def login_with_pin(pin: str):
	"""Create a real Frappe user session after verifying a personal POS PIN on
	an enrolled terminal."""
	# The POS lock action logs out first, so accept PINs only from Guest.
	if frappe.session.user != "Guest":
		frappe.throw(_("Log out before switching POS users."), frappe.PermissionError)

	terminal = _resolve_terminal_from_cookie()
	if not terminal:
		_reject_pin_login(reason="no_terminal")

	if _is_terminal_locked(terminal.terminal_id):
		_reject_pin_login(terminal=terminal, reason="locked", audit_status="Locked")

	pin = str(pin or "").strip()
	if not pin.isdigit() or not PIN_MIN_LENGTH <= len(pin) <= PIN_MAX_LENGTH:
		_register_terminal_failure(terminal.terminal_id)
		_reject_pin_login(terminal=terminal, reason="bad_format")

	user = _find_user_for_pin(pin, terminal.branch)
	if not user:
		_register_terminal_failure(terminal.terminal_id)
		_reject_pin_login(terminal=terminal, reason="no_match")

	# Re-check eligibility immediately before creating the session so disabling a
	# user, role, Branch assignment, or PIN setting takes effect without delay.
	if not is_eligible_pos_user(user) or not is_user_in_branch(user, terminal.branch):
		_register_terminal_failure(terminal.terminal_id)
		_reject_pin_login(terminal=terminal, reason="ineligible")

	_clear_terminal_failures(terminal.terminal_id)
	terminal.touch_last_seen()

	login_manager = getattr(frappe.local, "login_manager", None) or LoginManager()
	login_manager.login_as(user)
	_record_login("Logged in to URY POS with personal PIN", user, "Success")
	_record_audit("Success", terminal=terminal, user=user, reason="pin_login")

	return {
		"user": user,
		"full_name": frappe.utils.get_fullname(user),
		"redirect_to": "/pos",
	}
