# Copyright (c) 2026, Tridz Technologies Pvt. Ltd. and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document


class URYKOTItemExecution(Document):
	"""Item-grain execution row for a single URY KOT line item.

	This doctype is additive to the existing KOT-level compatibility record.
	It stores the production lifecycle per `URY KOT Items` row so each KOT
	item can move independently through QUEUED -> IN_PREPARATION -> READY ->
	SERVED without affecting the current print/realtime path on `URY KOT`.
	"""

	def before_insert(self):
		# `revision_key` identifies WHICH VERSION OF THE LINE is being
		# produced. It is deliberately NOT `idempotency_key`: that field is a
		# per-RPC replay token, regenerated by the client for every single
		# call and rewritten by `_transition` on every state change, so it
		# cannot also carry a stable line identity (this is the defect behind
		# the false "stale production posting" block at POS Invoice submit).
		#
		# Stamped here as a backstop so that every creation path -- the
		# service's `seed_kot_item_executions`, tests, and any future caller
		# -- yields a row with a revision, never NULL.
		if not self.revision_key:
			self.revision_key = frappe.generate_hash(length=32)
